# Generated by Django 5.0.4 on 2024-12-22 13:46

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=users.models.Role.admin, editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
