# Generated by Django 5.0.4 on 2024-10-12 13:15

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_user_phone_number_permission_rolepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, default=users.models.Role.admin, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
