# Generated by Django 5.0.4 on 2024-12-22 13:47

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=users.models.Role.super_admin, editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
