version: "3.8"
services:
  app:
    build: .
    ports:
      - 8000:8000
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=school_management_system
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=postgres
      - SQL_PORT=5432
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    image: school_management_system:app
    container_name: school_management_system_container
    command: gunicorn --bind 0.0.0.0:8000 --timeout 999 -w 2 school_management_system.wsgi:application

  postgres:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=school_management_system

volumes:
  postgres_data:
