# Generated by Django 5.0.4 on 2024-12-22 13:44

import base.models
import django.db.models.deletion
import utils.token_manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=utils.token_manager.generate_token, max_length=200)),
                ('expires_at', models.DateTimeField(default=utils.token_manager.token_expiry)),
                ('source_ip', models.GenericIPAddressField(blank=True, help_text='The originating IP Address.', null=True)),
                ('totp_key', models.CharField(blank=True, max_length=100, null=True)),
                ('totp_time_value', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.ForeignKey(default=base.models.State.activation_pending, on_delete=django.db.models.deletion.CASCADE, to='base.state')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
